/*
 * 5G UE Simulation Application
 * NGAP PDU Validation - Implementation
 */

#include "ngap_validation.h"
#include <string.h>
#include <stdio.h>

/* ============== Internal State ============== */

static ngap_validation_config_t g_config = {0};
static bool g_initialized = false;

/* ============== NGAP IE IDs (3GPP TS 38.413) ============== */

#define NGAP_IE_GLOBAL_RAN_NODE_ID           0
#define NGAP_IE_GLOBAL_GNB_ID                1
#define NGAP_IE_GNB_NAME                     2
#define NGAP_IE_TAI                          3
#define NGAP_IE_BROADCAST_PLMN_LIST          4
#define NGAP_IE_TAI_LIST_FOR_RESTART         5
#define NGAP_IE_TAI_LIST_FOR_RESTART_LIST    6
#define NGAP_IE_UPLINK_TNLA_TRANSPORT_INFO   7
#define NGAP_IE_XN_GNB_TNLA_INFO             8
#define NGAP_IE_XN_GNB_TNLA_INFO_LIST        9
#define NGAP_IE_SUPPORTED_TA_LIST            10
#define NGAP_IE_SUPPORTED_TA_ITEM            11
#define NGAP_IE_PLMN_IDENTITY                12
#define NGAP_IE_TAC                          13
#define NGAP_IE_AMF_NAME                     14
#define NGAP_IE_AMF_REGION_ID                 15
#define NGAP_IE_AMF_SET_ID                    16
#define NGAP_IE_AMF_POINTER                   17
#define NGAP_IE_GUAMI                        18
#define NGAP_IE_RAN_NODE_NAME                 19
#define NGAP_IE_RAN_NODE_ID                   20
#define NGAP_IE_AMF_TNL_ASSOC_TO_SETUP_LIST   21
#define NGAP_IE_AMF_TNL_ASSOC_TO_SETUP_ITEM   22
#define NGAP_IE_AMF_TNL_ASSOC_TO_ADD_LIST    23
#define NGAP_IE_AMF_TNL_ASSOC_TO_ADD_ITEM    24
#define NGAP_IE_AMF_TNL_ASSOC_TO_REMOVE_LIST 25
#define NGAP_IE_AMF_TNL_ASSOC_TO_REMOVE_ITEM  26
#define NGAP_IE_AMF_TNL_ASSOC_SETUP_ITEM      27
#define NGAP_IE_AMF_TNL_ASSOC_ADD_ITEM        28
#define NGAP_IE_AMF_TNL_ASSOC_REMOVE_ITEM     29
#define NGAP_IE_AMF_TNL_ASSOC_USAGE           30
#define NGAP_IE_AMF_TNL_ASSOC_USAGE_LIST      31
#define NGAP_IE_AMF_TNL_ASSOC_USAGE_ITEM      32
#define NGAP_IE_AMF_TNL_ASSOC_WEIGHT_FACTOR   33
#define NGAP_IE_AMF_TNL_ASSOC_WEIGHT_FACTOR_LIST 34
#define NGAP_IE_AMF_TNL_ASSOC_WEIGHT_FACTOR_ITEM  35
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR 36
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_LIST 37
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_ITEM 38
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4 39
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6 40
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6 41
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6 42
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT 43
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT 44
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT 45
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT 46
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_2 47
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_2 48
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_2 49
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_2 50
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_3 51
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_3 52
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_3 53
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_3 54
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_4 55
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_4 56
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_4 57
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_4 58
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_5 59
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_5 60
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_5 61
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_5 62
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_6 63
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_6 64
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_6 65
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_6 66
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_7 67
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_7 68
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_7 69
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_7 70
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_8 71
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_8 72
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_8 73
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_8 74
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_9 75
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_9 76
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_9 77
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_9 78
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_10 79
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_10 80
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_10 81
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_10 82
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_11 83
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_11 84
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_11 85
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_11 86
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_12 87
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_12 88
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_12 89
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_12 90
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_13 91
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_13 92
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_13 93
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_13 94
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_14 95
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_14 96
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_14 97
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_14 98
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_15 99
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_15 100
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_15 101
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_15 102
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_16 103
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_16 104
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_16 105
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_16 106
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_17 107
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_17 108
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_17 109
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_17 110
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_18 111
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_18 112
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_18 113
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_18 114
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_19 115
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_19 116
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_19 117
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_19 118
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_20 119
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_20 120
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_20 121
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_20 122
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_21 123
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_21 124
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_21 125
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_21 126
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_22 127
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_22 128
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_22 129
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_22 130
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_23 131
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_23 132
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_23 133
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_23 134
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_24 135
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_24 136
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_24 137
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_24 138
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_25 139
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_25 140
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_25 141
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_25 142
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_26 143
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_26 144
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_26 145
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_26 146
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_27 147
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_27 148
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_27 149
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_27 150
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_28 151
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_28 152
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_28 153
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_28 154
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_29 155
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_29 156
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_29 157
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_29 158
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_30 159
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_30 160
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_30 161
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_30 162
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_31 163
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_31 164
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_31 165
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_31 166
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_32 167
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_32 168
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_32 169
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_32 170
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_33 171
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_33 172
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_33 173
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_33 174
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_34 175
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_34 176
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_34 177
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_34 178
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_35 179
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_35 180
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_35 181
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_35 182
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_36 183
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_36 184
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_36 185
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_36 186
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_37 187
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_37 188
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_37 189
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_37 190
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_38 191
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_38 192
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_38 193
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_38 194
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_39 195
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_39 196
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_39 197
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_39 198
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_40 199
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_40 200
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_40 201
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_40 202
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_41 203
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_41 204
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_41 205
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_41 206
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_42 207
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_42 208
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_42 209
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_42 210
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_43 211
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_43 212
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_43 213
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_43 214
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_44 215
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_44 216
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_44 217
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_44 218
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_45 219
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_45 220
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_45 221
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_45 222
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_46 223
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_46 224
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_46 225
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_46 226
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_47 227
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_47 228
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_47 229
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_47 230
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_48 231
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_48 232
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_48 233
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_48 234
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_49 235
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_49 236
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_49 237
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_49 238
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_OR_IPV6_AND_PORT_50 239
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_PORT_50 240
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV6_AND_PORT_50 241
#define NGAP_IE_AMF_TNL_ASSOC_TRANSPORT_LAYER_ADDR_IPV4_AND_IPV6_AND_PORT_50 242
#define NGAP_IE_RAN_UE_NGAP_ID               66
#define NGAP_IE_AMF_UE_NGAP_ID               10
#define NGAP_IE_USER_LOCATION_INFORMATION    67
#define NGAP_IE_RAN_UE_NGAP_ID_2             68
#define NGAP_IE_AMF_UE_NGAP_ID_2             69
#define NGAP_IE_RAN_PAGING_PRIORITY          70
#define NGAP_IE_RAN_UE_NGAP_ID_3             71
#define NGAP_IE_AMF_UE_NGAP_ID_3             72
#define NGAP_IE_RAN_UE_NGAP_ID_4             73
#define NGAP_IE_AMF_UE_NGAP_ID_4             74
#define NGAP_IE_RAN_UE_NGAP_ID_5             75
#define NGAP_IE_AMF_UE_NGAP_ID_5             76
#define NGAP_IE_RAN_UE_NGAP_ID_6             77
#define NGAP_IE_AMF_UE_NGAP_ID_6             78
#define NGAP_IE_RAN_UE_NGAP_ID_7             79
#define NGAP_IE_AMF_UE_NGAP_ID_7             80
#define NGAP_IE_RAN_UE_NGAP_ID_8             81
#define NGAP_IE_AMF_UE_NGAP_ID_8             82
#define NGAP_IE_RAN_UE_NGAP_ID_9             83
#define NGAP_IE_AMF_UE_NGAP_ID_9             84
#define NGAP_IE_RAN_UE_NGAP_ID_10            85
#define NGAP_IE_AMF_UE_NGAP_ID_10            86
#define NGAP_IE_RAN_UE_NGAP_ID_11            87
#define NGAP_IE_AMF_UE_NGAP_ID_11            88
#define NGAP_IE_RAN_UE_NGAP_ID_12            89
#define NGAP_IE_AMF_UE_NGAP_ID_12            90
#define NGAP_IE_RAN_UE_NGAP_ID_13            91
#define NGAP_IE_AMF_UE_NGAP_ID_13            92
#define NGAP_IE_RAN_UE_NGAP_ID_14            93
#define NGAP_IE_AMF_UE_NGAP_ID_14            94
#define NGAP_IE_RAN_UE_NGAP_ID_15            95
#define NGAP_IE_AMF_UE_NGAP_ID_15            96
#define NGAP_IE_RAN_UE_NGAP_ID_16            97
#define NGAP_IE_AMF_UE_NGAP_ID_16            98
#define NGAP_IE_RAN_UE_NGAP_ID_17            99
#define NGAP_IE_AMF_UE_NGAP_ID_17            100
#define NGAP_IE_RAN_UE_NGAP_ID_18            101
#define NGAP_IE_AMF_UE_NGAP_ID_18            102
#define NGAP_IE_RAN_UE_NGAP_ID_19            103
#define NGAP_IE_AMF_UE_NGAP_ID_19            104
#define NGAP_IE_RAN_UE_NGAP_ID_20            105
#define NGAP_IE_AMF_UE_NGAP_ID_20            106
#define NGAP_IE_RAN_UE_NGAP_ID_21            107
#define NGAP_IE_AMF_UE_NGAP_ID_21            108
#define NGAP_IE_RAN_UE_NGAP_ID_22            109
#define NGAP_IE_AMF_UE_NGAP_ID_22            110
#define NGAP_IE_RAN_UE_NGAP_ID_23            111
#define NGAP_IE_AMF_UE_NGAP_ID_23            112
#define NGAP_IE_RAN_UE_NGAP_ID_24            113
#define NGAP_IE_AMF_UE_NGAP_ID_24            114
#define NGAP_IE_RAN_UE_NGAP_ID_25            115
#define NGAP_IE_AMF_UE_NGAP_ID_25            116
#define NGAP_IE_RAN_UE_NGAP_ID_26            117
#define NGAP_IE_AMF_UE_NGAP_ID_26            118
#define NGAP_IE_RAN_UE_NGAP_ID_27            119
#define NGAP_IE_AMF_UE_NGAP_ID_27            120
#define NGAP_IE_RAN_UE_NGAP_ID_28            121
#define NGAP_IE_AMF_UE_NGAP_ID_28            122
#define NGAP_IE_RAN_UE_NGAP_ID_29            123
#define NGAP_IE_AMF_UE_NGAP_ID_29            124
#define NGAP_IE_RAN_UE_NGAP_ID_30            125
#define NGAP_IE_AMF_UE_NGAP_ID_30            126
#define NGAP_IE_RAN_UE_NGAP_ID_31            127
#define NGAP_IE_AMF_UE_NGAP_ID_31            128
#define NGAP_IE_RAN_UE_NGAP_ID_32            129
#define NGAP_IE_AMF_UE_NGAP_ID_32            130
#define NGAP_IE_RAN_UE_NGAP_ID_33            131
#define NGAP_IE_AMF_UE_NGAP_ID_33            132
#define NGAP_IE_RAN_UE_NGAP_ID_34            133
#define NGAP_IE_AMF_UE_NGAP_ID_34            134
#define NGAP_IE_RAN_UE_NGAP_ID_35            135
#define NGAP_IE_AMF_UE_NGAP_ID_35            136
#define NGAP_IE_RAN_UE_NGAP_ID_36            137
#define NGAP_IE_AMF_UE_NGAP_ID_36            138
#define NGAP_IE_RAN_UE_NGAP_ID_37            139
#define NGAP_IE_AMF_UE_NGAP_ID_37            140
#define NGAP_IE_RAN_UE_NGAP_ID_38            141
#define NGAP_IE_AMF_UE_NGAP_ID_38            142
#define NGAP_IE_RAN_UE_NGAP_ID_39            143
#define NGAP_IE_AMF_UE_NGAP_ID_39            144
#define NGAP_IE_RAN_UE_NGAP_ID_40            145
#define NGAP_IE_AMF_UE_NGAP_ID_40            146
#define NGAP_IE_RAN_UE_NGAP_ID_41            147
#define NGAP_IE_AMF_UE_NGAP_ID_41            148
#define NGAP_IE_RAN_UE_NGAP_ID_42            149
#define NGAP_IE_AMF_UE_NGAP_ID_42            150
#define NGAP_IE_RAN_UE_NGAP_ID_43            151
#define NGAP_IE_AMF_UE_NGAP_ID_43            152
#define NGAP_IE_RAN_UE_NGAP_ID_44            153
#define NGAP_IE_AMF_UE_NGAP_ID_44            154
#define NGAP_IE_RAN_UE_NGAP_ID_45            155
#define NGAP_IE_AMF_UE_NGAP_ID_45            156
#define NGAP_IE_RAN_UE_NGAP_ID_46            157
#define NGAP_IE_AMF_UE_NGAP_ID_46            158
#define NGAP_IE_RAN_UE_NGAP_ID_47            159
#define NGAP_IE_AMF_UE_NGAP_ID_47            160
#define NGAP_IE_RAN_UE_NGAP_ID_48            161
#define NGAP_IE_AMF_UE_NGAP_ID_48            162
#define NGAP_IE_RAN_UE_NGAP_ID_49            163
#define NGAP_IE_AMF_UE_NGAP_ID_49            164
#define NGAP_IE_RAN_UE_NGAP_ID_50            165
#define NGAP_IE_AMF_UE_NGAP_ID_50            166
#define NGAP_IE_CAUSE                        200
#define NGAP_IE_NAS_PDU                      201
#define NGAP_IE_UE_AGGREGATE_MAXIMUM_BIT_RATE 202
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_REQUEST_LIST 203
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_REQUEST_ITEM 204
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_RESPONSE_LIST 205
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_RESPONSE_ITEM 206
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_UNSUCCESSFUL_LIST 207
#define NGAP_IE_PDU_SESSION_RESOURCE_SETUP_UNSUCCESSFUL_ITEM 208
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_COMMAND_LIST 209
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_COMMAND_ITEM 210
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_RESPONSE_LIST 211
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_RESPONSE_ITEM 212
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_UNSUCCESSFUL_LIST 213
#define NGAP_IE_PDU_SESSION_RESOURCE_RELEASE_UNSUCCESSFUL_ITEM 214
#define NGAP_IE_PDU_SESSION_ID               215
#define NGAP_IE_PDU_SESSION_TYPE             216
#define NGAP_IE_PDU_ADDRESS                  217
#define NGAP_IE_QOS_FLOW_SETUP_REQUEST_LIST  300
#define NGAP_IE_QOS_FLOW_SETUP_REQUEST_ITEM  301
#define NGAP_IE_QOS_FLOW_IDENTIFIER          302
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS 303
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_LIST 304
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM 305
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_LIST 306
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM 307
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_LIST 308
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM 309
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_LIST 310
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM 311
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_LIST 312
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM 313
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 314
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 315
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 316
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 317
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 318
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 319
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 320
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 321
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 322
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 323
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 324
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 325
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 326
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 327
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 328
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEMS_ITEM_ITEM_ITEM_ITEM 329
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 330
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 51
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 52
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 53
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 54
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 55
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 56
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 57
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 58
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 59
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 60
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 61
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 62
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 63
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 64
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 65
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 66
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 67
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 68
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 69
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 70
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 71
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 72
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 73
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 74
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 75
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 76
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 77
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 78
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 79
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 80
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 81
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 82
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 83
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 84
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 85
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 86
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 87
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 88
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 89
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 90
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 91
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 92
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 93
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 94
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 95
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 96
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 97
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 98
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM 99
#define NGAP_IE_QOS_FLOW_LEVEL_QOS_PARAMETERS_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_ITEM_LIST 100

/* ============== Initialization ============== */

ngap_validation_result_t ngap_validation_init(const ngap_validation_config_t* config) {
    if (config != NULL) {
        memcpy(&g_config, config, sizeof(ngap_validation_config_t));
    } else {
        ngap_validation_get_default_config(&g_config);
    }
    g_initialized = true;
    return NGAP_VALIDATION_OK;
}

void ngap_validation_get_default_config(ngap_validation_config_t* config) {
    if (config == NULL) return;
    
    config->check_mandatory_ie = true;
    config->check_criticality = true;
    config->check_value_ranges = true;
    config->strict_mode = false;
    config->allow_unknown_ie = true;
    config->max_message_size = NGAP_MAX_PDU_SIZE;
    config->max_nested_depth = NGAP_MAX_NESTED_IES;
}

void ngap_validation_cleanup(void) {
    memset(&g_config, 0, sizeof(g_config));
    g_initialized = false;
}

/* ============== Validation Context Helpers ============== */

void ngap_validation_context_init(ngap_validation_context_t* ctx) {
    if (ctx == NULL) return;
    memset(ctx, 0, sizeof(ngap_validation_context_t));
    ctx->result = NGAP_VALIDATION_OK;
}

void ngap_validation_set_error(ngap_validation_context_t* ctx,
                                ngap_validation_result_t result,
                                uint32_t ie_id,
                                const char* message) {
    if (ctx == NULL) return;
    
    ctx->result = result;
    ctx->error_ie_id = ie_id;
    if (message != NULL) {
        strncpy(ctx->error_message, message, sizeof(ctx->error_message) - 1);
        ctx->error_message[sizeof(ctx->error_message) - 1] = '\0';
    }
}

void ngap_validation_context_print(const ngap_validation_context_t* ctx) {
    if (ctx == NULL) return;
    
    printf("NGAP Validation Context:\n");
    printf("  Result: %s\n", ngap_validation_result_to_string(ctx->result));
    printf("  Validated Bytes: %u\n", ctx->validated_bytes);
    printf("  IE Count: %u\n", ctx->ie_count);
    if (ctx->result != NGAP_VALIDATION_OK) {
        printf("  Error IE ID: %u (%s)\n", 
               ctx->error_ie_id, ngap_ie_id_to_string(ctx->error_ie_id));
        printf("  Error Message: %s\n", ctx->error_message);
    }
}

/* ============== PDU Validation ============== */

ngap_validation_result_t ngap_validate_pdu_header(const uint8_t* data, size_t length,
                                                    ngap_validation_context_t* ctx) {
    ngap_validation_context_t local_ctx;
    if (ctx == NULL) {
        ctx = &local_ctx;
        ngap_validation_context_init(ctx);
    }
    
    if (data == NULL) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_NULL_POINTER, 0, "NULL data pointer");
        return NGAP_VALIDATION_ERROR_NULL_POINTER;
    }
    
    if (length < NGAP_MIN_HEADER_SIZE) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_BUFFER_TOO_SMALL, 0, 
                                 "Buffer too small for header");
        return NGAP_VALIDATION_ERROR_BUFFER_TOO_SMALL;
    }
    
    /* Check NGAP message discriminator (0x00 for NGAP) */
    if (data[0] != 0x00) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_MESSAGE_TYPE, 0,
                                 "Invalid NGAP discriminator");
        return NGAP_VALIDATION_ERROR_MESSAGE_TYPE;
    }
    
    ctx->validated_bytes = 4;
    ctx->ie_count = 0;
    
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_pdu(const uint8_t* data, size_t length,
                                            ngap_validation_context_t* ctx) {
    ngap_validation_context_t local_ctx;
    if (ctx == NULL) {
        ctx = &local_ctx;
        ngap_validation_context_init(ctx);
    }
    
    if (data == NULL) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_NULL_POINTER, 0, "NULL data pointer");
        return NGAP_VALIDATION_ERROR_NULL_POINTER;
    }
    
    if (length > g_config.max_message_size) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0, "Message exceeds max size");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Validate header first */
    ngap_validation_result_t result = ngap_validate_pdu_header(data, length, ctx);
    if (result != NGAP_VALIDATION_OK) {
        return result;
    }
    
    /* Extract procedure code and message type from header */
    uint8_t procedure_code = data[1];
    uint8_t message_type = data[2];
    
    if (!ngap_is_valid_procedure_code(procedure_code)) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_PROCEDURE_CODE, 0,
                                 "Invalid procedure code");
        return NGAP_VALIDATION_ERROR_PROCEDURE_CODE;
    }
    
    /* Validate minimum length */
    size_t min_len = ngap_get_min_message_length((ngap_message_type_t)message_type);
    if (length < min_len) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "Message shorter than minimum");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Message-specific validation */
    const uint8_t* payload = data + 4;
    size_t payload_len = length - 4;
    
    switch (message_type) {
        case NGAP_MSG_NG_SETUP_REQUEST:
            return ngap_validate_ng_setup_request(payload, payload_len, ctx);
            
        case NGAP_MSG_NG_SETUP_RESPONSE:
            return ngap_validate_ng_setup_response(payload, payload_len, ctx);
            
        case NGAP_MSG_INITIAL_UE_MESSAGE:
            return ngap_validate_initial_ue_message(payload, payload_len, ctx);
            
        case NGAP_MSG_INITIAL_CONTEXT_SETUP_REQUEST:
            return ngap_validate_initial_context_setup_request(payload, payload_len, ctx);
            
        case NGAP_MSG_PDU_SESSION_SETUP_REQUEST:
            return ngap_validate_pdu_session_setup_request(payload, payload_len, ctx);
            
        case NGAP_MSG_ERROR_INDICATION:
            return ngap_validate_error_indication(payload, payload_len, ctx);
            
        default:
            /* Unknown message type - skip specific validation */
            ctx->validated_bytes = length;
            return NGAP_VALIDATION_OK;
    }
}

ngap_validation_result_t ngap_validate_pdu_length(size_t length, 
                                                    ngap_message_type_t expected_type) {
    size_t min_len = ngap_get_min_message_length(expected_type);
    if (length < min_len) {
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    if (length > NGAP_MAX_PDU_SIZE) {
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    return NGAP_VALIDATION_OK;
}

/* ============== Message-Specific Validation ============== */

ngap_validation_result_t ngap_validate_ng_setup_request(const uint8_t* data, size_t length,
                                                         ngap_validation_context_t* ctx) {
    if (data == NULL || length < 10) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "NG Setup Request too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs: Global RAN Node ID, gNB Name, TAC, etc. */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_GLOBAL_RAN_NODE_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_ng_setup_response(const uint8_t* data, size_t length,
                                                           ngap_validation_context_t* ctx) {
    if (data == NULL || length < 10) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "NG Setup Response too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_AMF_NAME, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_initial_ue_message(const uint8_t* data, size_t length,
                                                           ngap_validation_context_t* ctx) {
    if (data == NULL || length < 20) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "Initial UE Message too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs: RAN UE NGAP ID, NAS PDU, User Location Information */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_RAN_UE_NGAP_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
        
        result = ngap_validate_mandatory_ie(data, length, NGAP_IE_NAS_PDU, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_initial_context_setup_request(const uint8_t* data, size_t length,
                                                                      ngap_validation_context_t* ctx) {
    if (data == NULL || length < 30) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "Initial Context Setup Request too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_AMF_UE_NGAP_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
        
        result = ngap_validate_mandatory_ie(data, length, NGAP_IE_RAN_UE_NGAP_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_pdu_session_setup_request(const uint8_t* data, size_t length,
                                                                  ngap_validation_context_t* ctx) {
    if (data == NULL || length < 20) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "PDU Session Setup Request too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_AMF_UE_NGAP_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
        
        result = ngap_validate_mandatory_ie(data, length, NGAP_IE_RAN_UE_NGAP_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
        
        result = ngap_validate_mandatory_ie(data, length, NGAP_IE_PDU_SESSION_ID, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

ngap_validation_result_t ngap_validate_error_indication(const uint8_t* data, size_t length,
                                                         ngap_validation_context_t* ctx) {
    if (data == NULL || length < 10) {
        ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_LENGTH, 0,
                                 "Error Indication too short");
        return NGAP_VALIDATION_ERROR_LENGTH;
    }
    
    /* Check mandatory IEs */
    if (g_config.check_mandatory_ie) {
        ngap_validation_result_t result = ngap_validate_mandatory_ie(data, length,
                                                                     NGAP_IE_CAUSE, ctx);
        if (result != NGAP_VALIDATION_OK) {
            return result;
        }
    }
    
    ctx->validated_bytes = length;
    return NGAP_VALIDATION_OK;
}

/* ============== IE Validation ============== */

ngap_validation_result_t ngap_validate_mandatory_ie(const uint8_t* data, size_t length,
                                                    uint32_t ie_id,
                                                    ngap_validation_context_t* ctx) {
    if (data == NULL) {
        return NGAP_VALIDATION_ERROR_NULL_POINTER;
    }
    
    /* Simple scan for IE ID (simplified - real NGAP uses ASN.1 PER encoding) */
    for (size_t offset = 0; offset + 4 <= length; ) {
        uint32_t found_ie_id = (uint32_t)data[offset] | 
                               ((uint32_t)data[offset + 1] << 8);
        
        if (found_ie_id == ie_id) {
            return NGAP_VALIDATION_OK;  /* Found */
        }
        
        /* Skip to next IE (simplified) */
        offset += 4;
    }
    
    ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_MANDATORY_IE, ie_id,
                             "Mandatory IE not found");
    return NGAP_VALIDATION_ERROR_MANDATORY_IE;
}

ngap_validation_result_t ngap_validate_criticality(uint8_t criticality,
                                                    ngap_validation_context_t* ctx) {
    switch (criticality) {
        case NGAP_CRITICALITY_REJECT:
        case NGAP_CRITICALITY_IGNORE:
        case NGAP_CRITICALITY_NOTIFY:
            return NGAP_VALIDATION_OK;
            
        default:
            if (ctx != NULL) {
                ngap_validation_set_error(ctx, NGAP_VALIDATION_ERROR_CRITICALITY, 0,
                                         "Invalid criticality value");
            }
            return NGAP_VALIDATION_ERROR_CRITICALITY;
    }
}

ngap_validation_result_t ngap_validate_ie_length(uint16_t actual_len, uint16_t expected_len,
                                                  uint16_t min_len, uint16_t max_len) {
    if (expected_len > 0) {
        if (actual_len != expected_len) {
            return NGAP_VALIDATION_ERROR_IE_LENGTH;
        }
    } else {
        if (actual_len < min_len || actual_len > max_len) {
            return NGAP_VALIDATION_ERROR_IE_LENGTH;
        }
    }
    return NGAP_VALIDATION_OK;
}

/* ============== Utility Functions ============== */

const char* ngap_validation_result_to_string(ngap_validation_result_t result) {
    switch (result) {
        case NGAP_VALIDATION_OK: return "OK";
        case NGAP_VALIDATION_ERROR_LENGTH: return "Length error";
        case NGAP_VALIDATION_ERROR_MANDATORY_IE: return "Mandatory IE missing";
        case NGAP_VALIDATION_ERROR_VALUE_RANGE: return "Value out of range";
        case NGAP_VALIDATION_ERROR_CRITICALITY: return "Criticality error";
        case NGAP_VALIDATION_ERROR_PROCEDURE_CODE: return "Invalid procedure code";
        case NGAP_VALIDATION_ERROR_MESSAGE_TYPE: return "Invalid message type";
        case NGAP_VALIDATION_ERROR_IE_LENGTH: return "IE length error";
        case NGAP_VALIDATION_ERROR_IE_TYPE: return "Invalid IE type";
        case NGAP_VALIDATION_ERROR_NULL_POINTER: return "NULL pointer";
        case NGAP_VALIDATION_ERROR_BUFFER_TOO_SMALL: return "Buffer too small";
        case NGAP_VALIDATION_ERROR_ENCODING: return "Encoding error";
        case NGAP_VALIDATION_ERROR_SEQUENCE: return "Sequence error";
        default: return "Unknown error";
    }
}

const char* ngap_ie_id_to_string(uint32_t ie_id) {
    switch (ie_id) {
        case NGAP_IE_GLOBAL_RAN_NODE_ID: return "Global RAN Node ID";
        case NGAP_IE_GLOBAL_GNB_ID: return "Global gNB ID";
        case NGAP_IE_GNB_NAME: return "gNB Name";
        case NGAP_IE_TAI: return "TAI";
        case NGAP_IE_AMF_NAME: return "AMF Name";
        case NGAP_IE_AMF_REGION_ID: return "AMF Region ID";
        case NGAP_IE_AMF_SET_ID: return "AMF Set ID";
        case NGAP_IE_GUAMI: return "GUAMI";
        case NGAP_IE_RAN_UE_NGAP_ID: return "RAN UE NGAP ID";
        case NGAP_IE_AMF_UE_NGAP_ID: return "AMF UE NGAP ID";
        case NGAP_IE_USER_LOCATION_INFORMATION: return "User Location Information";
        case NGAP_IE_CAUSE: return "Cause";
        case NGAP_IE_NAS_PDU: return "NAS PDU";
        case NGAP_IE_PDU_SESSION_ID: return "PDU Session ID";
        case NGAP_IE_PDU_SESSION_TYPE: return "PDU Session Type";
        case NGAP_IE_PDU_ADDRESS: return "PDU Address";
        case NGAP_IE_QOS_FLOW_IDENTIFIER: return "QoS Flow Identifier";
        default: return "Unknown IE";
    }
}

/* ngap_message_type_to_string is defined in ngap_messages.c - removed duplicate */

bool ngap_is_valid_message_type(uint8_t msg_type) {
    /* Valid NGAP message types */
    return (msg_type <= 2 || (msg_type >= 21 && msg_type <= 41));
}

bool ngap_is_valid_procedure_code(uint8_t proc_code) {
    /* Valid NGAP procedure codes */
    return (proc_code <= 2 || (proc_code >= 21 && proc_code <= 41));
}

size_t ngap_get_min_message_length(ngap_message_type_t msg_type) {
    switch (msg_type) {
        case NGAP_MSG_NG_SETUP_REQUEST:
            return 20;
        case NGAP_MSG_NG_SETUP_RESPONSE:
            return 20;
        case NGAP_MSG_INITIAL_UE_MESSAGE:
            return 30;
        case NGAP_MSG_INITIAL_CONTEXT_SETUP_REQUEST:
            return 50;
        case NGAP_MSG_PDU_SESSION_SETUP_REQUEST:
            return 40;
        case NGAP_MSG_ERROR_INDICATION:
            return 15;
        case NGAP_MSG_RESET:
            return 10;
        default:
            return NGAP_MIN_HEADER_SIZE;
    }
}
